[package]
name = "raspare"
version = "0.1.0"
edition = "2024"

[dependencies]
# parser
ariadne = "0.5.1"
chumsky = "1.0.0-alpha.8"
# images
image = "0.25.6"
ndarray = { version = "0.16.1", features = ["rayon"] }
rayon = "1.10.0"

# perf
peak_alloc = "0.2.1"
